INSERT INTO TB_CATEGORIA (DESCRICAO) VALUES('CURSO')
INSERT INTO TB_CATEGORIA (DESCRICAO) VALUES('OFICINA')

INSERT INTO TB_PARTICIPANTE(NOME,EMAIL) VALUES('JOSE SILVA', 'JOSE@GMAIL.COM')
INSERT INTO TB_PARTICIPANTE(NOME,EMAIL) VALUES('TIAGO FARIA', 'TIAGO@GMAIL.COM')
INSERT INTO TB_PARTICIPANTE(NOME,EMAIL) VALUES('MARIA DO ROSARIO', 'MARIA@GMAIL.COM')
INSERT INTO TB_PARTICIPANTE(NOME,EMAIL) VALUES('TEREZA SILVA', 'TEREZA@GMAIL.COM')

INSERT INTO TB_ATIVIDADE(NOME,DESCRICAO,PRECO,ID_CATEGORIA) VALUES('CURSO HTML','APREDA HTML DE FORMA PRATICA',80.00,1)
INSERT INTO TB_ATIVIDADE(NOME,DESCRICAO,PRECO,ID_CATEGORIA) VALUES('OFICINA DE GIT','CONTROLE DE VERSÕES DE SEUS PROJETOS',50.00,2)

INSERT INTO TB_PARTICIPANTE_ATIVIDADE(ID_ATIVIDADE,ID_PARTICIPANTE) VALUES(1,1)
INSERT INTO TB_PARTICIPANTE_ATIVIDADE(ID_ATIVIDADE,ID_PARTICIPANTE) VALUES(1,3)
INSERT INTO TB_PARTICIPANTE_ATIVIDADE(ID_ATIVIDADE,ID_PARTICIPANTE) VALUES(2,1)
INSERT INTO TB_PARTICIPANTE_ATIVIDADE(ID_ATIVIDADE,ID_PARTICIPANTE) VALUES(2,3)
INSERT INTO TB_PARTICIPANTE_ATIVIDADE(ID_ATIVIDADE,ID_PARTICIPANTE) VALUES(2,4)

INSERT INTO TB_BLOCO(INICIO,FIM,ID_ATIVIDADE) VALUES('2017-09-25T08:00:00Z','2017-09-25T11:00:00Z',1)
INSERT INTO TB_BLOCO(INICIO,FIM,ID_ATIVIDADE) VALUES('2017-09-25T14:00:00Z','2017-09-25T18:00:00Z',2)
INSERT INTO TB_BLOCO(INICIO,FIM,ID_ATIVIDADE) VALUES('2017-09-26T08:00:00Z','2017-09-25T11:00:00Z',2)
